name: Atualizar Imóvel

on:
  repository_dispatch:
    types: [update_imovel]  # 👈 Deve bater com o event_type do frontend

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Atualizar JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # 1. Cria arquivo com o novo imóvel
          echo '${{ toJSON(github.event.client_payload.imovel) }}' > novo-imovel.json
          
          # 2. Atualiza o arquivo principal (cria se não existir)
          if [ -f "site/imoveis.json" ]; then
            jq '. += [input]' site/imoveis.json novo-imovel.json > temp.json
            mv temp.json site/imoveis.json
          else
            mkdir -p site
            echo '[]' > site/imoveis.json
            jq '. += [input]' site/imoveis.json novo-imovel.json > temp.json
            mv temp.json site/imoveis.json
          fi
          
          # 3. Commit e push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add site/imoveis.json
          git commit -m "Adiciona imóvel via admin"
          git push
