name: Atualizar Imóveis

on:
  repository_dispatch:
    types: [update_imovel]  # Deve bater com o event_type do seu frontend

jobs:
  update_json:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixa o código do repositório
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para o git push funcionar

      # 2. Configura o Git
      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3. Processa o novo imóvel
      - name: Atualizar arquivo JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Token com permissões
        run: |
          # Cria arquivo temporário com os dados recebidos
          echo '${{ toJSON(github.event.client_payload.imovel) }}' > novo-imovel.json

          # Verifica se o arquivo principal existe
          if [ -f "site/imoveis.json" ]; then
            echo "Arquivo existente encontrado, adicionando novo imóvel..."
            jq '. += [input]' site/imoveis.json novo-imovel.json > temp.json
          else
            echo "Arquivo não existe, criando novo..."
            mkdir -p site
            jq -n '[input]' novo-imovel.json > temp.json
          fi

          # Substitui o arquivo antigo
          mv temp.json site/imoveis.json

          # Faz commit das mudanças
          git add site/imoveis.json
          git commit -m "Adiciona imóvel via painel admin [skip ci]"
          git push origin HEAD:${{ github.ref }}
